apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc01
  labels:
    app: vpromc

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vpromc

  template:
    metadata:
      labels:
        app: vpromc

    spec:
      containers:
        - name: memcached
          image: memcached
          ports:
            - name: memcached
              containerPort: 11211
